// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://planghjxwhftapqjknfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYW5naGp4d2hmdGFwcWprbmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODc2OTEsImV4cCI6MjA1ODU2MzY5MX0.JkMEkOwOFl2JAVKOYvrqYbsV_mrTlU6GTVwIEQYKer4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);